# Generated by Django 2.0.3 on 2018-04-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villages',
            options={},
        ),
    ]
