# Generated by Django 2.2.10 on 2022-05-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220524_1555'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['village_id'], name='village_id'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['village_name'], name='village_name'),
        ),
        migrations.AddIndex(
            model_name='villages',
            index=models.Index(fields=['tehsil_id'], name='tehsil_id'),
        ),
        migrations.AddIndex(
            model_name='villages',
            index=models.Index(fields=['district_id'], name='district_id'),
        ),
        migrations.AddIndex(
            model_name='villages',
            index=models.Index(fields=['vid'], name='vid'),
        ),
    ]
