# Generated by Django 2.0.3 on 2018-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180426_1333'),
    ]

    operations = [        
    ]
