# Generated by Django 2.2.10 on 2021-05-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180426_1437'),
    ]

    operations = [
    ]
