# Generated by Django 2.2.10 on 2021-05-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210525_1924'),
    ]

    operations = [
    ]
