# Generated by Django 2.2.10 on 2021-05-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210525_1956'),
    ]

    operations = []
