# Generated by Django 2.2.10 on 2021-06-29 15:36

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20210615_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '830x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
    ]
