# Generated by Django 2.2.10 on 2021-07-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20210629_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='theme',
            field=models.ManyToManyField(blank=True, default=None, to='interviews.Theme'),
        ),
    ]
