# Generated by Django 2.2.10 on 2021-07-03 23:25

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_video_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='clip',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '830x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='themes/'),
        ),
        migrations.AddField(
            model_name='video',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '830x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
    ]
