# Generated by Django 2.2.10 on 2021-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_auto_20210705_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='clip_youtube_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='clip',
            name='clip_vimeo_id',
            field=models.CharField(blank=True, help_text='Vimeo ID, if uploaded as a separate clip', max_length=200, verbose_name='vimeo ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='vimeo ID'),
        ),
    ]
