# Generated by Django 2.2.10 on 2021-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_auto_20210705_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='clip_vimeo_id',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='image',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='image_cropping',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='start_time',
        ),
        migrations.AddField(
            model_name='clip',
            name='end_time_minutes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='clip',
            name='end_time_seconds',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='clip',
            name='start_time_minutes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='clip',
            name='start_time_seconds',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
