# Generated by Django 2.2.10 on 2021-07-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_auto_20210705_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background_image',
            field=models.ImageField(blank=True, max_length=200, upload_to='images/'),
        ),
    ]
