# Generated by Django 2.2.10 on 2021-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_page_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('village_name', models.CharField(max_length=256)),
                ('village_name_pb', models.CharField(blank=True, max_length=256, null=True)),
                ('tehsil', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('district_id', models.IntegerField()),
                ('tehsil_id', models.IntegerField()),
                ('vid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('lon', models.CharField(blank=True, max_length=16, null=True)),
                ('lat', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'villages',
                'managed': False,
            },
        ),
    ]
