# Generated by Django 2.2.10 on 2021-07-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0014_video_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='village',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
