# Generated by Django 2.2.10 on 2021-07-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0016_auto_20210706_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='district',
        ),
        migrations.AddField(
            model_name='video',
            name='classification',
            field=models.CharField(blank=True, choices=[('1', 'Enforced Disappearance'), ('2', 'Extrajudicial Execution')], max_length=24),
        ),
        migrations.AlterField(
            model_name='video',
            name='combatant_status',
            field=models.CharField(blank=True, choices=[('1', 'Combatant'), ('0', 'Non-Combatant'), ('9', 'Unknown')], max_length=14),
        ),
        migrations.AlterField(
            model_name='video',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=6),
        ),
    ]
