# Generated by Django 2.2.10 on 2021-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0017_auto_20210708_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.DateField(blank=True),
        ),
    ]
