# Generated by Django 2.2.10 on 2021-10-17 12:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0020_auto_20210924_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
