# Generated by Django 2.2.10 on 2021-10-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0021_auto_20211017_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='year',
            new_name='date_range_start',
        ),
    ]
