# Generated by Django 2.2.10 on 2021-10-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0022_auto_20211027_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_range_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
