# Generated by Django 2.2.10 on 2021-10-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0023_video_date_range_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='age',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
