# Generated by Django 2.2.10 on 2021-11-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0024_auto_20211031_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(blank=True, max_length=200)),
                ('profile_id', models.CharField(blank=True, max_length=10, verbose_name='data.ensaaf.org Profile ID')),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=6)),
                ('age', models.CharField(blank=True, max_length=6)),
                ('combatant_status', models.CharField(blank=True, choices=[('1', 'Combatant'), ('0', 'Non-Combatant'), ('9', 'Unknown')], max_length=14)),
                ('classification', models.CharField(blank=True, choices=[('1', 'Enforced Disappearance'), ('2', 'Extrajudicial Execution')], max_length=24)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=10, verbose_name='Village Census Code')),
                ('video', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='interviews.Video')),
            ],
        ),
    ]
