# Generated by Django 2.2.10 on 2021-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0025_victim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='age',
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='video',
            name='classification',
            field=models.CharField(blank=True, choices=[('1', 'Enforced Disappearance'), ('2', 'Extrajudicial Execution')], editable=False, max_length=24),
        ),
        migrations.AlterField(
            model_name='video',
            name='combatant_status',
            field=models.CharField(blank=True, choices=[('1', 'Combatant'), ('0', 'Non-Combatant'), ('9', 'Unknown')], editable=False, max_length=14),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_range_end',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_range_start',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='video',
            name='profile_id',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='data.ensaaf.org Profile ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='village',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Village Census Code'),
        ),
    ]
