# Generated by Django 2.2.10 on 2021-05-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('youtube_id', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('combatant_status', models.CharField(blank=True, choices=[('Combatant', 'Combatant'), ('Non-Combatant', 'Non-Combatant'), ('Unknown', 'Unknown')], max_length=14)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('district', models.CharField(blank=True, choices=[('302', 'Amritsar'), ('314', 'Bathinda'), ('313', 'Faridkot'), ('308', 'Fatehgarh Sahib'), ('311', 'Firozpur'), ('301', 'Gurdaspur'), ('305', 'Hoshiarpur'), ('304', 'Jalandhar'), ('303', 'Kapurthala'), ('309', 'Ludhiana'), ('315', 'Mansa'), ('310', 'Moga'), ('312', 'Muktsar'), ('306', 'Nawanshahr'), ('317', 'Patiala'), ('307', 'Rupnagar'), ('316', 'Sangrur')], max_length=14)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=8)),
                ('end_time', models.CharField(blank=True, max_length=8)),
                ('theme', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.Theme')),
                ('video', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
        ),
    ]
