# Generated by Django 2.2.10 on 2021-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='theme',
        ),
        migrations.AddField(
            model_name='clip',
            name='theme',
            field=models.ManyToManyField(blank=True, default=None, to='video.Theme'),
        ),
    ]
