# Generated by Django 2.2.10 on 2021-05-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210525_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='clip',
            name='clip_youtube_id',
            field=models.CharField(blank=True, help_text='YouTube ID, if uploaded as a separate clip', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='YouTube ID', max_length=200),
        ),
    ]
