# Generated by Django 2.2.10 on 2021-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20210528_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='clip_youtube_id',
            field=models.CharField(blank=True, help_text='YouTube ID, if uploaded as a separate clip', max_length=200, verbose_name='YouTube ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='YouTube ID'),
        ),
    ]
