# Generated by Django 2.2.10 on 2021-06-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20210604_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
