# Generated by Django 2.2.10 on 2021-06-04 17:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
