# Generated by Django 2.2.10 on 2021-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20210604_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background_video',
            field=models.FileField(blank=True, upload_to='video/', verbose_name='Background Video'),
        ),
    ]
