# Generated by Django 2.2.10 on 2021-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_page_background_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='tags',
        ),
        migrations.AlterField(
            model_name='clip',
            name='clip_vimeo_id',
            field=models.CharField(blank=True, help_text='Vimeo ID, if uploaded as a separate clip', max_length=200, verbose_name='vimeo ID'),
        ),
    ]
